version: 2
jobs:
    test-py3: &test-template
        docker:
            - image: circleci/python:3.5.7
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: "Install Python requirements"
                command: |
                    sudo pip install -Ur requirements.txt
                    sudo python setup.py install
            - run:
                name: "Run tests"
                command: pytest --cov=chaospy chaospy tests

            - run:
                name: "Coverage report"
                command: codecov
    test-py2:
        <<: *test-template
        docker:
            - image: circleci/python:2.7.16
    documentation:
        <<: *test-template
        steps:
            - checkout
            - run:
                name: "Install Python requirements"
                command: |
                    sudo pip install -Ur requirements.txt
                    sudo python setup.py install
            - run:
                name: "Ensure documentation build"
                command: sphinx-build doc/ doc/.build -b html -n -v --color -T -W
workflows:
    version: 2
    test:
        jobs:
            - test-py3
            - test-py2
            - documentation
